# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0002_auto_20151205_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='statement_descriptor',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
