# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0002_auto_20151205_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinreceiver',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='charge',
            name='amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='amount_refunded',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transferchargefee',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
