# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0005_auto_20161006_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business_name', models.TextField(blank=True)),
                ('business_primary_color', models.TextField(blank=True)),
                ('business_url', models.TextField(blank=True)),
                ('charges_enabled', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=2)),
                ('debit_negative_balances', models.BooleanField(default=False)),
                ('decline_charge_on_avs_failure', models.BooleanField(default=False)),
                ('decline_charge_on_cvc_failure', models.BooleanField(default=False)),
                ('default_currency', models.CharField(max_length=3)),
                ('details_submitted', models.BooleanField(default=False)),
                ('display_name', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('legal_entity_address_city', models.TextField(blank=True, null=True)),
                ('legal_entity_address_country', models.TextField(blank=True, null=True)),
                ('legal_entity_address_line1', models.TextField(blank=True, null=True)),
                ('legal_entity_address_line2', models.TextField(blank=True, null=True)),
                ('legal_entity_address_postal_code', models.TextField(blank=True, null=True)),
                ('legal_entity_address_state', models.TextField(blank=True, null=True)),
                ('legal_entity_dob', models.DateField(null=True)),
                ('legal_entity_first_name', models.TextField(blank=True, null=True)),
                ('legal_entity_gender', models.TextField(blank=True, null=True)),
                ('legal_entity_last_name', models.TextField(blank=True, null=True)),
                ('legal_entity_maiden_name', models.TextField(blank=True, null=True)),
                ('legal_entity_personal_id_number_provided', models.BooleanField(default=False)),
                ('legal_entity_phone_number', models.TextField(blank=True, null=True)),
                ('legal_entity_ssn_last_4_provided', models.BooleanField(default=False)),
                ('legal_entity_type', models.TextField(blank=True, null=True)),
                ('legal_entity_verification_details', models.TextField(blank=True, null=True)),
                ('legal_entity_verification_details_code', models.TextField(blank=True, null=True)),
                ('legal_entity_verification_document', models.TextField(blank=True, null=True)),
                ('legal_entity_verification_status', models.TextField(blank=True, null=True)),
                ('managed', models.NullBooleanField()),
                ('metadata', jsonfield.fields.JSONField(null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('statement_descriptor', models.TextField(blank=True, null=True)),
                ('support_email', models.TextField(blank=True, null=True)),
                ('support_phone', models.TextField(blank=True, null=True)),
                ('support_url', models.TextField(blank=True, null=True)),
                ('timezone', models.TextField(blank=True, null=True)),
                ('tos_acceptance_date', models.DateField(null=True)),
                ('tos_acceptance_ip', models.TextField(blank=True, null=True)),
                ('tos_acceptance_user_agent', models.TextField(blank=True, null=True)),
                ('transfer_schedule_delay_days', models.PositiveSmallIntegerField(null=True)),
                ('transfer_schedule_interval', models.TextField(blank=True, null=True)),
                ('transfer_schedule_monthly_anchor', models.PositiveSmallIntegerField(null=True)),
                ('transfer_schedule_weekly_anchor', models.TextField(blank=True, null=True)),
                ('transfer_statement_descriptor', models.TextField(blank=True, null=True)),
                ('transfers_enabled', models.BooleanField(default=False)),
                ('verification_disabled_reason', models.TextField(blank=True, null=True)),
                ('verification_due_by', models.DateTimeField(blank=True, null=True)),
                ('verification_timestamp', models.DateTimeField(blank=True, null=True)),
                ('verification_fields_needed', jsonfield.fields.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_holder_name', models.TextField()),
                ('account_holder_type', models.TextField()),
                ('bank_name', models.TextField()),
                ('country', models.TextField()),
                ('currency', models.TextField()),
                ('default_for_currency', models.BooleanField(default=False)),
                ('fingerprint', models.TextField()),
                ('last4', models.CharField(max_length=4)),
                ('metadata', jsonfield.fields.JSONField(null=True)),
                ('routing_number', models.TextField()),
                ('status', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinax_stripe.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transfer',
            name='amount_reversed',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='balance_transaction',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='destination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='destination_payment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='failure_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='livemode',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='metadata',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='source_transaction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='source_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='statement_descriptor',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='pinax_stripe.Event'),
        ),
    ]
