# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-02 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0007_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='fee_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
