# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0007_auto_20170108_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('type', models.CharField(blank=True, max_length=32)),
                ('usage', models.CharField(blank=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('flow', models.CharField(max_length=32)),
                ('livemode', models.BooleanField(default=False)),
                ('owner_address', models.TextField(blank=True)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('owner_name', models.TextField(blank=True)),
                ('owner_phone', models.TextField(blank=True)),
                ('owner_verified_address', models.TextField(blank=True)),
                ('owner_verified_email', models.EmailField(blank=True, max_length=254)),
                ('owner_verified_name', models.TextField(blank=True)),
                ('owner_verified_phone', models.TextField(blank=True)),
                ('redirect_return_url', models.URLField(max_length=1024)),
                ('redirect_status', models.TextField(blank=True)),
                ('redirect_url', models.URLField(max_length=1024)),
                ('ideal_bank', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinax_stripe.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
