# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-17 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0007_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charge',
            name='available_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
