# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-18 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0008_auto_20170316_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='transfer_group',
            field=models.TextField(blank=True, null=True),
        ),
    ]
