# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0008_auto_20161227_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='amount_reversed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='application_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='balance_transaction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='pinax_stripe.Event'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='failure_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='metadata',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='source_transaction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='source_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='statement_descriptor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
