# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 00:27
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0008_auto_20170509_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='metadata',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
