# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0009_auto_20170825_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=191, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('routing_number', models.CharField(max_length=35)),
                ('account_holder_type', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(blank=True, max_length=4)),
                ('funding', models.CharField(max_length=15)),
                ('last4', models.CharField(blank=True, max_length=4)),
                ('fingerprint', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinax_stripe.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
