# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0009_auto_20161227_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='livemode',
            field=models.NullBooleanField(default=None),
        ),
    ]
