# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0010_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
