# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-06 20:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0011_auto_20171121_1648_fix_step1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='stripe_account',
        ),
        migrations.RemoveField(
            model_name='event',
            name='stripe_account',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='stripe_account'
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='stripe_account',
        ),
        migrations.AddField(
            model_name='customer',
            name='stripe_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='pinax_stripe.Account'),
        ),
        migrations.AddField(
            model_name='event',
            name='stripe_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='pinax_stripe.Account'),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='pinax_stripe.Account'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='stripe_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='pinax_stripe.Account'),
        ),
    ]
