# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0010_connect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='display_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
