# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-06 20:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pinax_stripe', '0010_connect'),
    ]

    operations = [

    ]
