# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-19 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0010_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing',
            field=models.CharField(default='charge_automatically', max_length=32),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='forgiven',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='metadata',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing',
            field=models.CharField(default='charge_automatically', max_length=32),
        ),
        migrations.AddField(
            model_name='subscription',
            name='days_until_due',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='application_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
