# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-26 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0011_auto_20171019_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billing',
            field=models.CharField(choices=[('charge_automatically', 'Charge automatically'), ('send_invoice', 'Send invoice')], default='charge_automatically', max_length=32),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing',
            field=models.CharField(choices=[('charge_automatically', 'Charge automatically'), ('send_invoice', 'Send invoice')], default='charge_automatically', max_length=32),
        ),
    ]
