# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0011_auto_20171024_1209'),
        ('pinax_stripe', '0011_auto_20171017_1234'),
    ]

    operations = [
    ]
