# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0011_rename_account_transfers_payout'),
        ('pinax_stripe', '0011_auto_20171121_1648'),
    ]

    operations = [
    ]
