# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0012_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_account',
        ),
    ]
