# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0013_transfer_transfer_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='balance_transaction',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='livemode',
        ),
    ]
