# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-30 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0013_auto_20171025_2153'),
        ('pinax_stripe', '0012_auto_20171026_1544'),
    ]

    operations = [
    ]
