# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0011_account_publishable_key'),
        ('pinax_stripe', '0013_auto_20171025_2153'),
    ]

    operations = [
    ]
