# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0014_auto_20180413_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
