# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-31 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0014_auto_20180413_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('flat_amount', models.IntegerField()),
                ('up_to', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='billing_scheme',
            field=models.CharField(default='per_unit', max_length=15),
        ),
        migrations.AddField(
            model_name='plan',
            name='tiers_mode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tier',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='pinax_stripe.Plan'),
        ),
    ]
