# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-20 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0014_auto_20180413_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AlterModelOptions(
            name='bitcoinreceiver',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AlterModelOptions(
            name='charge',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'get_latest_by': 'created_at'},
        ),
    ]
