# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0014_auto_20170302_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='failure_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
