# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-05 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0013_charge_outcome'),
        ('pinax_stripe', '0014_merge_20171030_1242'),
    ]

    operations = [
    ]
