# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0014_blank_with_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='legal_entity_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
