# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0014_auto_20171018_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='stripe_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinax_stripe.Account'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stripe_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinax_stripe.Account'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='stripe_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinax_stripe.Account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='stripe_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinax_stripe.Account'),
        ),
    ]
