# Generated by Django 2.2a1 on 2019-02-01 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0014_auto_20180413_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='billing_scheme',
            field=models.CharField(default='per_unit', max_length=15),
        ),
        migrations.AddField(
            model_name='plan',
            name='tiers_mode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField()),
                ('flat_amount', models.DecimalField()),
                ('up_to', models.DecimalField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='pinax_stripe.Plan')),
            ],
        ),
    ]
