# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0013_auto_20171027_1443'),
        ('pinax_stripe', '0014_merge_20171030_1554'),
    ]

    operations = [
    ]
