# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pinax_stripe', '0015_account-as-foreign-key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraccount',
            unique_together=set([('user', 'customer')]),
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='account',
        ),
    ]
