# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-16 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0015_blank_account_legal_entity_dob'),
        ('pinax_stripe', '0014_auto_20180413_1959'),
    ]

    operations = [
    ]
