# Generated by Django 2.1.5 on 2019-04-22 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0015_auto_20190120_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='request',
        ),
    ]
