# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0015_plan_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='percent_off',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
