# Generated by Django 3.2.9 on 2021-11-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0015_get_latest_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='captured',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='disputed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='paid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='refunded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='valid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='attempted',
            field=models.BooleanField(null=True),
        ),
    ]
