# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0015_transfer_failure_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='method',
            field=models.TextField(blank=True, null=True),
        ),
    ]
