# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-03 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0016_transfer_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='source',
        ),
        migrations.AddField(
            model_name='transfer',
            name='livemode',
            field=models.BooleanField(default=False),
        ),
    ]
