# Generated by Django 2.2.24 on 2021-08-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0016_merge_20180416_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
