# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0016_account_authorized'),
        ('pinax_stripe', '0016_auto_20171106_1234'),
    ]

    operations = [
    ]
