# Generated by Django 3.1 on 2020-08-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0016_remove_event_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='valid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
