# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-26 15:42
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0017_auto_20180619_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='metadata',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
