# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0017_merge_20171106_2201'),
        ('pinax_stripe', '0017_merge_20171106_2109'),
    ]

    operations = [
    ]
