# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-03 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0017_auto_20170302_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripe_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='stripe_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='stripe_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
