# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-07 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0018_auto_20170303_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='pinax_stripe.Event'),
        ),
    ]
