# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0012_merge_20171025_1443'),
        ('pinax_stripe', '0018_add_discounts'),
    ]

    operations = [
    ]
