# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-06-23 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0018_invoice_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PauseCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior', models.CharField(blank=True, choices=[('keep_as_draft', 'keep_as_draft'), ('mark_uncollectible', 'mark_uncollectible'), ('void', 'void')], default=None, max_length=20, null=True)),
                ('resumes_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='pause_collection',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='pinax_stripe.PauseCollection'),
        ),
    ]
