# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0020_account-publishablke-key'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='authorized',
            field=models.BooleanField(default=True),
        ),
    ]
