# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0013_auto_20171027_1443'),
        ('pinax_stripe', '0022_sub-account-related'),
    ]

    operations = [
    ]
