# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0023_merge_20171027_1626'),
        ('pinax_stripe', '0015_merge_20171030_1852'),
    ]

    operations = [
    ]
