# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0024_merge_20171030_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_account',
        ),
    ]
