# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0017_merge_20171106_2201'),
        ('pinax_stripe', '0025_remove_subscription_stripe_account'),
    ]

    operations = [
    ]
